### ISSUE TITLE
Error installing the new version

### ISSUE THREAD

**Issue by yccteam** [arei/npmbox#28]
When trying to install the new version, I get the following errors:
```
C:\Users\YONK\Documents\libs\npmbox\npmbox>npm install --verbose --global --cache ./.npmbox.cache --optional --cache-min 99999 npmbox
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '--global',
npm verb cli   '--cache',
npm verb cli   './.npmbox.cache',
npm verb cli   '--optional',
npm verb cli   '--cache-min',
npm verb cli   '99999',
npm verb cli   'npmbox' ]
npm info using npm@2.5.1
npm info using node@v0.12.0
npm verb node symlink C:\Program Files\nodejs\\node.exe
npm verb cache add spec npmbox
npm verb addTmpTarball C:\Users\YONK\Documents\libs\npmbox\npmbox\npmbox not in flight; adding
npm verb addTmpTarball validating metadata from C:\Users\YONK\Documents\libs\npmbox\npmbox\npmbox
npm verb tar unpack C:\Users\YONK\Documents\libs\npmbox\npmbox\npmbox
npm verb tar unpacking to C:\Users\YONK\AppData\Local\Temp\npm-6456-67c70f8d\unpack-3b1a8d48127e
npm verb gentlyRm vacuuming C:\Users\YONK\AppData\Local\Temp\npm-6456-67c70f8d\unpack-3b1a8d48127e
npm ERR! addLocal Could not install C:\Users\YONK\Documents\libs\npmbox\npmbox\npmbox
npm verb stack Error: ENOENT, open 'C:\Users\YONK\AppData\Local\Temp\npm-6456-67c70f8d\unpack-3b1a8d48127e\package.json'
npm verb stack     at Error (native)
npm verb cwd C:\Users\YONK\Documents\libs\npmbox\npmbox
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "--global" "--cache" "./.npmbox.cache" "--optional" "--cache-min" "99999" "npmbox"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path C:\Users\YONK\AppData\Local\Temp\npm-6456-67c70f8d\unpack-3b1a8d48127e\package.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'C:\Users\YONK\AppData\Local\Temp\npm-6456-67c70f8d\unpack-3b1a8d48127e\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm verb exit [ -4058, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\YONK\Documents\libs\npmbox\npmbox\npm-debug.log
```

**Comment by Sub-Star** [comment]
I got this error message when trying this as well. In my case, it was caused by doing the following on the offline machine:
- I copied the npmbox.npmbox file to my offline computer.
- I used 7-Zip to extract the contents of npmbox.npmbox to a folder (like c:\temp\), which was a single file: npmbox
- I used 7-Zip to extract the contents of npmbox to the same folder (c:\temp\), which was the .npmbox.cache folder.
- I ran the command: npm install --verbose --global --cache ./.npmbox.cache --optional --cache-min 99999 npmbox

After some digging, I figured out that npm is actually trying to install the package from the npmbox file (c:\temp\npmbox) because that file is a tar-ball. Removing that file, leaving the .npmbox.cache folder, fixed this issue for me.

**Comment by arei** [comment]
Added note to documentation regarding file name.

**Comment by Sub-Star** [comment]
@arei I've read your note in the documentation, and I feel you missed the mark just a little bit with it. What I found was that it wasn't the `npmbox.npmbox` file that was the problem, it was the file named `npmbox` (notice no extension in the filename) inside `npmbox.npmbox` that was causing the problem. 

I was using 7-Zip (on Windows), and I had to extract twice. First I extracted from `npmbox.npmbox` (into the same folder) and got that extensionless file named `npmbox`. Then I extracted from `npmbox` (into the same folder) and got the `.npmbox.cache` folder. So when I got that error I had the following structure in c:\temp\:
- .npmbox.cache  -  folder
- npmbox  -  file
- npmbox.npmbox  -  file

That extensionless file matches the packagename in the npm install command, and therefore npm install thinks that it should use `npmbox` as package source instead of the `.npmbox.cache` folder.
Does this make sense to you?

**Comment by arei** [comment]
Yes, you're right, I did miss that. And I think you mentioned somewhere before this is due to the nature of how a .tar.gz file is stored (aka first the file is tar'd and then that tar'd file is zipped.)

I will change the nature of the note to describe how best to unzip on windows and the nature of dealing with .tar.gz files on windows.

**Comment by Sub-Star** [comment]
Thank you for listening @arei =)
I was not aware of the structure of .tar.gz files, and me not using the tar command on Windows explained why I wasn't seeing the same thing as the documentation described I would.
I guess you learn something new every day. ;)

**Comment by desmond-phonegap** [comment]
This has not still resolved the issue for me. My case I have removed the npmbox.npmbox file and only unziped .npmbox.cache file is there in the folder that i run the install version.

**Comment by arei** [comment]
@desmond-phonegap please create a new issues.  Also, add as much detail as you can and a log of possible.
